prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'blackbox-external-targets'
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            -  http://192.168.49.2:32264
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-prometheus-blackbox-exporter:9115

      - job_name: "blackbox-kubernetes-services"
        metrics_path: /probe
        params:
          module: [http_2xx]
        kubernetes_sd_configs:
        - role: service
        relabel_configs:
        # Example relabel to probe only some services that have "example.io/should_be_probed = true" annotation
        #  - source_labels: [__meta_kubernetes_service_annotation_example_io_should_be_probed]
        #    action: keep
        #    regex: true
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement:  prometheus-blackbox-prometheus-blackbox-exporter:9115
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_service_name


